INSERT INTO ROOM(ID, NAME, FLOOR_NB) VALUES(1, 'Room1', 1);
INSERT INTO ROOM(ID, NAME, FLOOR_NB) VALUES(2, 'Room2', 1);

INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (1, 8, 'ON', 1);
INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (2, 0, 'OFF', 1);
INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (3, 11, 'OFF', 1);
INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (4, 6, 'OFF', 2);
INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (5, 8, 'OFF', 2);
INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (6, 17, 'OFF', 2);